version: '1.0.{build}'
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: Any CPU
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore src -v Minimal
build_script:
- dotnet build "src\CheetahTesting" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\CheetahTesting.Tests" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet pack "src\CheetahTesting" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
test_script:
- dotnet test "src/CheetahTesting.Tests" -c %CONFIGURATION%